# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.CharField(max_length=255, unique=True, verbose_name='Token FCM')),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web (PWA)')], max_length=10, verbose_name='Plataforma')),
                ('nombre_dispositivo', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Dispositivo')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('version_app', models.CharField(blank=True, max_length=20, verbose_name='Versión de la App')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('total_notificaciones_enviadas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Notificaciones Enviadas')),
                ('total_notificaciones_fallidas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Notificaciones Fallidas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_moviles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo Móvil',
                'verbose_name_plural': 'Dispositivos Móviles',
                'db_table': 'dispositivo_movil',
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('calificacion', '📝 Nueva Calificación'), ('asistencia', '📅 Registro de Asistencia'), ('evaluacion', '📋 Nueva Evaluación'), ('alerta', '⚠️ Alerta Académica'), ('sistema', 'ℹ️ Información del Sistema'), ('tarea_nueva', '📚 Nueva Tarea'), ('tarea_entregada', '📤 Tarea Entregada'), ('tarea_calificada', '✅ Tarea Calificada'), ('anuncio_nuevo', '📢 Nuevo Anuncio'), ('mensaje_nuevo', '💬 Mensaje Nuevo'), ('comunicado_nuevo', '📋 Nuevo Comunicado'), ('evento_nuevo', '📅 Nuevo Evento'), ('citacion_nueva', '👥 Nueva Citación'), ('noticia_nueva', '📰 Nueva Noticia'), ('urgente_nuevo', '🚨 Comunicado Urgente')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enlace', models.CharField(blank=True, max_length=300, null=True, verbose_name='Enlace')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['destinatario', 'fecha_creacion'], name='notificacio_destina_9e2a92_idx'), models.Index(fields=['destinatario', 'leido'], name='notificacio_destina_4582fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('calificacion', '📝 Nueva Calificación'), ('asistencia', '📅 Registro de Asistencia'), ('evaluacion', '📋 Nueva Evaluación'), ('alerta', '⚠️ Alerta Académica'), ('sistema', 'ℹ️ Información del Sistema'), ('tarea_nueva', '📚 Nueva Tarea'), ('tarea_entregada', '📤 Tarea Entregada'), ('tarea_calificada', '✅ Tarea Calificada'), ('anuncio_nuevo', '📢 Nuevo Anuncio'), ('mensaje_nuevo', '💬 Mensaje Nuevo'), ('comunicado_nuevo', '📋 Nuevo Comunicado'), ('evento_nuevo', '📅 Nuevo Evento'), ('citacion_nueva', '👥 Nueva Citación'), ('noticia_nueva', '📰 Nueva Noticia'), ('urgente_nuevo', '🚨 Comunicado Urgente')], max_length=20, verbose_name='Tipo de Notificación')),
                ('canal_web', models.BooleanField(default=True, verbose_name='Web/Aplicación')),
                ('canal_email', models.BooleanField(default=False, verbose_name='Correo Electrónico')),
                ('canal_push', models.BooleanField(default=True, verbose_name='Notificación Push')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
                'db_table': 'preferencia_notificacion',
                'ordering': ['usuario', 'tipo_notificacion'],
                'unique_together': {('usuario', 'tipo_notificacion')},
            },
        ),
    ]
