# Generated by Django 5.2.9 on 2026-03-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivomovil',
            options={'ordering': ['-ultima_actividad'], 'verbose_name': 'Dispositivo Movil', 'verbose_name_plural': 'Dispositivos Moviles'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='preferencianotificacion',
            options={'ordering': ['usuario', 'tipo_notificacion'], 'verbose_name': 'Preferencia de Notificacion', 'verbose_name_plural': 'Preferencias de Notificaciones'},
        ),
        migrations.AlterField(
            model_name='dispositivomovil',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actividad'),
        ),
        migrations.AlterField(
            model_name='dispositivomovil',
            name='version_app',
            field=models.CharField(blank=True, max_length=20, verbose_name='Version de la App'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leido'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('calificacion', 'Nueva Calificacion'), ('asistencia', 'Registro de Asistencia'), ('evaluacion', 'Nueva Evaluacion'), ('alerta', 'Alerta Academica'), ('sistema', 'Informacion del Sistema'), ('tarea_nueva', 'Nueva Tarea'), ('tarea_entregada', 'Tarea Entregada'), ('tarea_calificada', 'Tarea Calificada'), ('anuncio_nuevo', 'Nuevo Anuncio'), ('mensaje_nuevo', 'Mensaje Nuevo'), ('comunicado_nuevo', 'Nuevo Comunicado'), ('evento_nuevo', 'Nuevo Evento'), ('citacion_nueva', 'Nueva Citacion'), ('noticia_nueva', 'Nueva Noticia'), ('urgente_nuevo', 'Comunicado Urgente')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='canal_email',
            field=models.BooleanField(default=False, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='canal_push',
            field=models.BooleanField(default=True, verbose_name='Notificacion Push'),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='canal_web',
            field=models.BooleanField(default=True, verbose_name='Web/Aplicacion'),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Modificacion'),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='tipo_notificacion',
            field=models.CharField(choices=[('calificacion', 'Nueva Calificacion'), ('asistencia', 'Registro de Asistencia'), ('evaluacion', 'Nueva Evaluacion'), ('alerta', 'Alerta Academica'), ('sistema', 'Informacion del Sistema'), ('tarea_nueva', 'Nueva Tarea'), ('tarea_entregada', 'Tarea Entregada'), ('tarea_calificada', 'Tarea Calificada'), ('anuncio_nuevo', 'Nuevo Anuncio'), ('mensaje_nuevo', 'Mensaje Nuevo'), ('comunicado_nuevo', 'Nuevo Comunicado'), ('evento_nuevo', 'Nuevo Evento'), ('citacion_nueva', 'Nueva Citacion'), ('noticia_nueva', 'Nueva Noticia'), ('urgente_nuevo', 'Comunicado Urgente')], max_length=20, verbose_name='Tipo de Notificacion'),
        ),
    ]
