# Generated by Django 5.2.9 on 2026-01-08 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(choices=[('tester', 'Tester (Ilimitado)'), ('trial', 'Prueba (30 días)'), ('basic', 'Básico'), ('standard', 'Estándar'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_unlimited', models.BooleanField(default=False, help_text='Plan TESTER: sin límites, para demos y desarrollo')),
                ('is_trial', models.BooleanField(default=False, help_text='Plan TRIAL: 30 días de prueba con límites')),
                ('duracion_dias', models.IntegerField(blank=True, help_text='Duración del plan en días (solo para TRIAL)', null=True)),
                ('max_estudiantes', models.IntegerField(default=999999, help_text='Número máximo de estudiantes activos')),
                ('max_profesores', models.IntegerField(default=999999, help_text='Número máximo de profesores activos')),
                ('max_cursos', models.IntegerField(default=999999, help_text='Número máximo de cursos activos')),
                ('max_mensajes_mes', models.IntegerField(default=999999, help_text='Mensajes por mes')),
                ('max_evaluaciones_mes', models.IntegerField(default=999999, help_text='Evaluaciones por mes')),
                ('max_almacenamiento_mb', models.IntegerField(default=999999, help_text='Almacenamiento en MB')),
                ('max_comunicados_mes', models.IntegerField(default=999999, help_text='Comunicados por mes')),
                ('has_attendance', models.BooleanField(default=True, help_text='Módulo de asistencia')),
                ('has_grades', models.BooleanField(default=True, help_text='Módulo de calificaciones')),
                ('has_messaging', models.BooleanField(default=True, help_text='Mensajería interna')),
                ('has_reports', models.BooleanField(default=False, help_text='Reportes básicos')),
                ('has_advanced_reports', models.BooleanField(default=False, help_text='Reportes avanzados y analytics')),
                ('has_file_attachments', models.BooleanField(default=True, help_text='Adjuntar archivos')),
                ('has_webpay_integration', models.BooleanField(default=False, help_text='Integración Webpay')),
                ('has_api_access', models.BooleanField(default=False, help_text='Acceso a API REST')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Soporte prioritario')),
                ('has_custom_branding', models.BooleanField(default=False, help_text='Personalización de marca')),
                ('activo', models.BooleanField(default=True)),
                ('orden_visualizacion', models.IntegerField(default=0, help_text='Orden para mostrar')),
                ('destacado', models.BooleanField(default=False, help_text='Marcar como plan destacado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'db_table': 'plan',
                'ordering': ['orden_visualizacion', 'precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_pago', models.DateField(blank=True, null=True)),
                ('proximo_pago', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('suspended', 'Suspendida')], default='active', max_length=20)),
                ('auto_renovar', models.BooleanField(default=True, help_text='Renovar automáticamente al vencer')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre la suscripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='institucion.colegio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_anio', models.IntegerField()),
                ('periodo_mes', models.IntegerField()),
                ('student_count', models.IntegerField(default=0, help_text='Estudiantes activos actuales')),
                ('teacher_count', models.IntegerField(default=0, help_text='Profesores activos actuales')),
                ('course_count', models.IntegerField(default=0, help_text='Cursos activos actuales')),
                ('messages_sent', models.IntegerField(default=0, help_text='Mensajes enviados este mes')),
                ('evaluations_created', models.IntegerField(default=0, help_text='Evaluaciones creadas este mes')),
                ('storage_used_mb', models.IntegerField(default=0, help_text='Almacenamiento usado en MB')),
                ('comunicados_sent', models.IntegerField(default=0, help_text='Comunicados enviados este mes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'db_table': 'usage_log',
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'fecha_fin'], name='subscriptio_status_6f0fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_dde032_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['subscription', 'periodo_anio', 'periodo_mes'], name='usage_log_subscri_f04e66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together={('subscription', 'periodo_anio', 'periodo_mes')},
        ),
    ]
