# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciaAdministrativa',
            fields=[
                ('id_dependencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Dependencia Administrativa',
                'verbose_name_plural': 'Dependencias Administrativas',
                'db_table': 'dependencia_administrativa',
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbd_colegio', models.IntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Sala de Clases', '🚪 Sala de Clases'), ('Laboratorio', '🔬 Laboratorio'), ('Biblioteca', '📚 Biblioteca'), ('Gimnasio', '🏃 Gimnasio'), ('Comedor', '🍽️ Comedor'), ('Auditorio', '🎭 Auditorio'), ('Sala de Profesores', '👨\u200d🏫 Sala de Profesores'), ('Oficina Administrativa', '💼 Oficina Administrativa'), ('Baños', '🚻 Baños'), ('Patio', '🌳 Patio'), ('Cancha Deportiva', '⚽ Cancha Deportiva'), ('Otro', '🏢 Otro')], max_length=50)),
                ('piso', models.IntegerField(default=1)),
                ('capacidad_estudiantes', models.IntegerField(default=0)),
                ('ancho_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('largo_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alto_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('Operativo', '✅ Operativo'), ('En Mantenimiento', '🔧 En Mantenimiento'), ('Fuera de Servicio', '❌ Fuera de Servicio')], default='Operativo', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infraestructura',
                'verbose_name_plural': 'Infraestructura',
                'db_table': 'infraestructura',
                'ordering': ['tipo', 'piso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'db_table': 'nivel_educativo',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id_tipo_establecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Establecimiento',
                'verbose_name_plural': 'Tipos de Establecimientos',
                'db_table': 'tipo_establecimiento',
            },
        ),
        migrations.CreateModel(
            name='TipoInfraestructura',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Infraestructura',
                'verbose_name_plural': 'Tipos de Infraestructura',
                'db_table': 'tipo_infraestructura',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='institucion.region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
                'unique_together': {('nombre', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('rbd', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_establecimiento', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colegios', to='institucion.comuna')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institucion.dependenciaadministrativa')),
                ('tipo_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institucion.tipoestablecimiento')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'colegio',
            },
        ),
        migrations.CreateModel(
            name='ColegioInfraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraestructura', to='institucion.colegio')),
                ('tipo_infra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institucion.tipoinfraestructura')),
            ],
            options={
                'verbose_name': 'Infraestructura del Colegio',
                'verbose_name_plural': 'Infraestructuras de Colegios',
                'db_table': 'colegio_infraestructura',
                'unique_together': {('colegio', 'tipo_infra')},
            },
        ),
    ]
