# Generated by Django 5.2.9 on 2026-01-27 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_niveleducativo_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ejemplo: '2024-2025'", max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('ACTIVO', 'Activo'), ('EVALUACION', 'En Evaluación'), ('FINALIZADO', 'Finalizado'), ('CERRADO', 'Cerrado')], default='PLANIFICACION', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_academicos', to='institucion.colegio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo Académico',
                'verbose_name_plural': 'Ciclos Académicos',
                'db_table': 'ciclo_academico',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_inicio__lt', models.F('fecha_fin'))), name='ciclo_fechas_validas')],
                'unique_together': {('colegio', 'nombre')},
            },
        ),
    ]
