# Generated by Django 6.0.1 on 2026-03-16 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0005_cicloacademico_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcademica',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_colegio', models.CharField(choices=[('MUNICIPAL', 'Municipal'), ('PARTICULAR_SUBVENCIONADO', 'Particular Subvencionado'), ('PARTICULAR_PAGADO', 'Particular Pagado'), ('TECNICO_PROFESIONAL', 'Tecnico Profesional')], default='MUNICIPAL', max_length=30)),
                ('nota_minima', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('nota_maxima', models.DecimalField(decimal_places=1, default=7.0, max_digits=3)),
                ('nota_aprobacion', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('periodo_evaluativo', models.CharField(choices=[('SEMESTRE', 'Semestre'), ('TRIMESTRE', 'Trimestre'), ('BIMESTRE', 'Bimestre')], default='SEMESTRE', max_length=20)),
                ('requiere_firma_docente', models.BooleanField(default=True)),
                ('exportar_sige_automatico', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_academica', to='institucion.colegio')),
            ],
            options={
                'verbose_name': 'Configuracion Academica',
                'verbose_name_plural': 'Configuraciones Academicas',
                'db_table': 'configuracion_academica',
                'constraints': [models.CheckConstraint(condition=models.Q(('nota_minima__lt', models.F('nota_maxima'))), name='config_nota_min_menor_nota_max'), models.CheckConstraint(condition=models.Q(('nota_aprobacion__gte', models.F('nota_minima')), ('nota_aprobacion__lte', models.F('nota_maxima'))), name='config_nota_aprobacion_en_rango')],
            },
        ),
    ]
