# Generated by Django 5.2.9 on 2026-01-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_claseestudiante'),
        ('institucion', '0003_cicloacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciclo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='institucion.cicloacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('colegio', 'nombre', 'ciclo_academico')},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='anio_escolar',
        ),
    ]
