# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('horas_semanales', models.IntegerField(default=0)),
                ('color', models.CharField(default='#667eea', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='institucion.colegio')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
                'unique_together': {('colegio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('anio_escolar', models.IntegerField(default=2025)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='institucion.colegio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institucion.niveleducativo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'unique_together': {('colegio', 'nombre', 'anio_escolar')},
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='cursos.asignatura')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='institucion.colegio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_impartidas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
                'unique_together': {('colegio', 'curso', 'asignatura', 'profesor')},
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id_bloque', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('bloque_numero', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='institucion.colegio')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='cursos.clase')),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horarios',
                'db_table': 'bloque_horario',
                'ordering': ['dia_semana', 'bloque_numero'],
                'unique_together': {('colegio', 'dia_semana', 'bloque_numero', 'clase')},
            },
        ),
    ]
