# Generated by Django 5.2.9 on 2026-01-25 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEstudiante',
            fields=[
                ('id_clase_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='cursos.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_matriculadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante en Clase',
                'verbose_name_plural': 'Estudiantes en Clases',
                'db_table': 'clase_estudiante',
                'unique_together': {('clase', 'estudiante')},
            },
        ),
    ]
