[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
testpaths = tests
addopts = --reuse-db
markers =
	django_db: mark test as requiring database access
	websocket_realtime: mark test that validates realtime websocket dispatch path
pythonpath = .
