# Generated by Codex on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_fix_foreignkey_integrity'),
        ('accounts', '0003_fix_foreignkey_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='curso_actual_id',
            field=models.ForeignKey(
                blank=True,
                db_column='curso_actual_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='perfiles_estudiante_legacy',
                to='cursos.curso',
            ),
        ),
    ]
