# Generated by Django 5.2.9 on 2026-03-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_new_operational_roles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rolecapability',
            new_name='role_capabi_role_id_9fd834_idx',
            old_name='role_capabi_role_id_53e9db_idx',
        ),
    ]
