# Generated by Django 5.2.9 on 2026-03-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_role_capabi_role_id_53e9db_idx_role_capabi_role_id_9fd834_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='estudiantes',
            field=models.ManyToManyField(limit_choices_to={'role__nombre': 'Estudiante'}, related_name='apoderados', through='accounts.RelacionApoderadoEstudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firmadigitalapoderado',
            name='estudiante',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__nombre': 'Estudiante'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firmas_apoderado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relacionapoderadoestudiante',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role__nombre': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_apoderados', to=settings.AUTH_USER_MODEL),
        ),
    ]
