# Generated by Django 5.2.9 on 2026-05-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_perfilstudiante_foto_perfil'),
        ('accounts', '0012_seed_fase1_libro_capabilities'),
    ]

    operations = [
    ]
