import { lazy } from 'react';

const DashboardEntryPage = lazy(() => import('../features/dashboard/DashboardEntryPage'));
const TeacherClassesPage = lazy(() => import('../features/profesor/TeacherClassesPage'));
const TeacherAttendancePage = lazy(() => import('../features/profesor/TeacherAttendancePage'));
const TeacherEvaluationsPage = lazy(() => import('../features/profesor/TeacherEvaluationsPage'));
const TeacherGradesPage = lazy(() => import('../features/profesor/TeacherGradesPage'));
const StudentSelfPage = lazy(() => import('../features/estudiante/StudentSelfPage'));
const AdminStudentsPage = lazy(() => import('../features/admin_escolar/AdminStudentsPage'));
const AdminOverviewPage = lazy(() => import('../features/admin_escolar/AdminOverviewPage'));
const AdminCoursesPage = lazy(() => import('../features/admin_escolar/AdminCoursesPage'));
const AdminClassesPage = lazy(() => import('../features/admin_escolar/AdminClassesPage'));
const AdminEvaluationsPage = lazy(() => import('../features/admin_escolar/AdminEvaluationsPage'));
const AdminGradesPage = lazy(() => import('../features/admin_escolar/AdminGradesPage'));
const AdminAttendancePage = lazy(() => import('../features/admin_escolar/AdminAttendancePage'));
const AdminImportExportPage = lazy(() => import('../features/admin_escolar/AdminImportExportPage'));
const CalendarEventsPage = lazy(() => import('../features/calendar/CalendarEventsPage'));
const MeetingRequestsPage = lazy(() => import('../features/reuniones/MeetingRequestsPage'));
const ActiveSessionsPage = lazy(() => import('../features/security/ActiveSessionsPage'));
const PasswordHistoryPage = lazy(() => import('../features/security/PasswordHistoryPage'));
const AsesorFinancieroPage = lazy(() => import('../features/asesor_financiero/AsesorFinancieroPage'));
const InspectorConvivenciaPage = lazy(() => import('../features/inspector_convivencia/InspectorConvivenciaPage'));
const PsicologoOrientadorPage = lazy(() => import('../features/psicologo_orientador/PsicologoOrientadorPage'));
const SoporteTecnicoPage = lazy(() => import('../features/soporte_tecnico/SoporteTecnicoPage'));
const BibliotecarioDigitalPage = lazy(() => import('../features/bibliotecario_digital/BibliotecarioDigitalPage'));
const CoordinadorAcademicoPage = lazy(() => import('../features/coordinador_academico/CoordinadorAcademicoPage'));
const ApoderadoPage = lazy(() => import('../features/apoderado/ApoderadoPage'));
const PricingPage = lazy(() => import('../features/subscriptions/PricingPage'));
const PaymentHistoryPage = lazy(() => import('../features/subscriptions/PaymentHistoryPage'));
const TransferNoticesPage = lazy(() => import('../features/subscriptions/TransferNoticesPage'));

export const APP_ROUTES = [
  {
    path: 'dashboard',
    to: '/dashboard',
    label: 'Inicio',
    component: DashboardEntryPage,
    anyOf: ['DASHBOARD_VIEW_SELF', 'DASHBOARD_VIEW_SCHOOL', 'DASHBOARD_VIEW_ANALYTICS'],
  },
  {
    path: 'admin-escolar/panel',
    to: '/admin-escolar/panel',
    label: 'Panel administrativo',
    component: AdminOverviewPage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['DASHBOARD_VIEW_SCHOOL', 'DASHBOARD_VIEW_ANALYTICS'],
  },
  {
    path: 'admin-escolar/estudiantes',
    to: '/admin-escolar/estudiantes',
    label: 'Estudiantes',
    component: AdminStudentsPage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['STUDENT_EDIT', 'STUDENT_CREATE', 'SYSTEM_CONFIGURE'],
    allOf: ['DASHBOARD_VIEW_SCHOOL'],
  },
  {
    path: 'admin-escolar/cursos',
    to: '/admin-escolar/cursos',
    label: 'Cursos',
    component: AdminCoursesPage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['COURSE_EDIT', 'COURSE_CREATE', 'SYSTEM_CONFIGURE'],
    allOf: ['DASHBOARD_VIEW_SCHOOL'],
  },
  {
    path: 'admin-escolar/clases',
    to: '/admin-escolar/clases',
    label: 'Clases',
    component: AdminClassesPage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['CLASS_EDIT', 'CLASS_CREATE', 'SYSTEM_CONFIGURE'],
    allOf: ['DASHBOARD_VIEW_SCHOOL'],
  },
  {
    path: 'admin-escolar/evaluaciones',
    to: '/admin-escolar/evaluaciones',
    label: 'Evaluaciones',
    component: AdminEvaluationsPage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['GRADE_EDIT', 'GRADE_CREATE', 'SYSTEM_CONFIGURE'],
    allOf: ['DASHBOARD_VIEW_SCHOOL'],
  },
  {
    path: 'admin-escolar/calificaciones',
    to: '/admin-escolar/calificaciones',
    label: 'Calificaciones',
    component: AdminGradesPage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['GRADE_EDIT', 'GRADE_CREATE', 'SYSTEM_CONFIGURE'],
    allOf: ['DASHBOARD_VIEW_SCHOOL'],
  },
  {
    path: 'admin-escolar/asistencias',
    to: '/admin-escolar/asistencias',
    label: 'Asistencias',
    component: AdminAttendancePage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['CLASS_TAKE_ATTENDANCE', 'SYSTEM_CONFIGURE'],
    allOf: ['DASHBOARD_VIEW_SCHOOL'],
  },
  {
    path: 'admin-escolar/importacion-exportacion',
    to: '/admin-escolar/importacion-exportacion',
    label: 'Importar y exportar',
    component: AdminImportExportPage,
    allowedRoles: ['admin_escolar', 'admin_general'],
    anyOf: ['SYSTEM_ADMIN', 'SYSTEM_CONFIGURE'],
    allOf: ['DASHBOARD_VIEW_SCHOOL'],
  },
  {
    path: 'calendario/eventos',
    to: '/calendario/eventos',
    label: 'Calendario escolar',
    component: CalendarEventsPage,
    anyOf: ['ANNOUNCEMENT_VIEW', 'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_EDIT', 'ANNOUNCEMENT_DELETE', 'SYSTEM_ADMIN'],
  },
  {
    path: 'reuniones/solicitudes',
    to: '/reuniones/solicitudes',
    label: 'Solicitudes',
    component: MeetingRequestsPage,
    allowedRoles: ['profesor', 'apoderado', 'admin_escolar', 'admin_general'],
    anyOf: ['CLASS_VIEW', 'SYSTEM_CONFIGURE', 'SYSTEM_ADMIN'],
  },
  {
    path: 'seguridad/sesiones-activas',
    to: '/seguridad/sesiones-activas',
    label: 'Sesiones activas',
    component: ActiveSessionsPage,
    anyOf: ['AUDIT_VIEW', 'SYSTEM_ADMIN'],
  },
  {
    path: 'seguridad/password-history',
    to: '/seguridad/password-history',
    label: 'Historial de claves',
    component: PasswordHistoryPage,
    anyOf: ['AUDIT_VIEW', 'SYSTEM_ADMIN'],
  },
  {
    path: 'profesor/clases',
    to: '/profesor/clases',
    label: 'Mis clases',
    component: TeacherClassesPage,
    allowedRoles: ['profesor'],
    anyOf: ['CLASS_VIEW'],
  },
  {
    path: 'profesor/mis-clases',
    to: '/profesor/mis-clases',
    label: 'Mis clases',
    component: TeacherClassesPage,
    allowedRoles: ['profesor'],
    anyOf: ['CLASS_VIEW'],
    hidden: true,
  },
  {
    path: 'profesor/asistencias',
    to: '/profesor/asistencias',
    label: 'Asistencias',
    component: TeacherAttendancePage,
    allowedRoles: ['profesor'],
    anyOf: ['CLASS_VIEW_ATTENDANCE', 'CLASS_TAKE_ATTENDANCE'],
  },
  {
    path: 'profesor/asistencia',
    to: '/profesor/asistencia',
    label: 'Asistencia',
    component: TeacherAttendancePage,
    allowedRoles: ['profesor'],
    anyOf: ['CLASS_VIEW_ATTENDANCE', 'CLASS_TAKE_ATTENDANCE'],
    hidden: true,
  },
  {
    path: 'profesor/evaluaciones',
    to: '/profesor/evaluaciones',
    label: 'Evaluaciones',
    component: TeacherEvaluationsPage,
    allowedRoles: ['profesor'],
    anyOf: ['GRADE_VIEW', 'GRADE_CREATE', 'GRADE_EDIT', 'GRADE_DELETE'],
  },
  {
    path: 'profesor/notas',
    to: '/profesor/notas',
    label: 'Evaluaciones y notas',
    component: TeacherGradesPage,
    allowedRoles: ['profesor'],
    anyOf: ['GRADE_VIEW', 'GRADE_CREATE', 'GRADE_EDIT', 'GRADE_DELETE'],
    hidden: true,
  },
  {
    path: 'profesor/calificaciones',
    to: '/profesor/calificaciones',
    label: 'Calificaciones',
    component: TeacherGradesPage,
    allowedRoles: ['profesor'],
    anyOf: ['GRADE_VIEW', 'GRADE_CREATE', 'GRADE_EDIT', 'GRADE_DELETE'],
  },
  {
    path: 'estudiante/panel',
    to: '/estudiante/panel',
    label: 'Mi panel',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/inicio',
    to: '/estudiante/inicio',
    label: 'Inicio',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/mis-clases',
    to: '/estudiante/mis-clases',
    label: 'Mis clases',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/mi-horario',
    to: '/estudiante/mi-horario',
    label: 'Mi horario',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/mis-notas',
    to: '/estudiante/mis-notas',
    label: 'Mis notas',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/mis-evaluaciones',
    to: '/estudiante/mis-evaluaciones',
    label: 'Mis evaluaciones',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/asistencia',
    to: '/estudiante/asistencia',
    label: 'Asistencia',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/mi-asistencia',
    to: '/estudiante/mi-asistencia',
    label: 'Mi asistencia',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/perfil',
    to: '/estudiante/perfil',
    label: 'Mi perfil',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/historial',
    to: '/estudiante/historial',
    label: 'Historial academico',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/mis-anotaciones',
    to: '/estudiante/mis-anotaciones',
    label: 'Mis anotaciones',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/tareas',
    to: '/estudiante/tareas',
    label: 'Mis tareas',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/calendario-tareas',
    to: '/estudiante/calendario-tareas',
    label: 'Calendario de tareas',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/comunicados',
    to: '/estudiante/comunicados',
    label: 'Comunicados',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/mensajes',
    to: '/estudiante/mensajes',
    label: 'Mensajes',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'estudiante/mis-certificados',
    to: '/estudiante/mis-certificados',
    label: 'Mis certificados',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/estado-cuenta',
    to: '/estudiante/estado-cuenta',
    label: 'Estado de cuenta',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/mis-pagos',
    to: '/estudiante/mis-pagos',
    label: 'Mis pagos',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
    hidden: true,
  },
  {
    path: 'estudiante/dashboard-graficos',
    to: '/estudiante/dashboard-graficos',
    label: 'Graficos del dashboard',
    component: StudentSelfPage,
    allowedRoles: ['estudiante', 'alumno'],
    anyOf: ['PORTAL_ESTUDIANTE'],
  },
  {
    path: 'asesor-financiero/panel',
    to: '/asesor-financiero/panel',
    label: 'Panel financiero',
    component: AsesorFinancieroPage,
    allowedRoles: ['asesor_financiero'],
    anyOf: ['FINANCE_VIEW', 'FINANCE_MANAGE_PAYMENTS'],
  },
  {
    path: 'inspector-convivencia/panel',
    to: '/inspector-convivencia/panel',
    label: 'Panel convivencia',
    component: InspectorConvivenciaPage,
    allowedRoles: ['inspector_convivencia'],
    anyOf: ['DISCIPLINE_VIEW', 'DISCIPLINE_CREATE', 'JUSTIFICATION_APPROVE'],
  },
  {
    path: 'psicologo-orientador/panel',
    to: '/psicologo-orientador/panel',
    label: 'Panel orientacion',
    component: PsicologoOrientadorPage,
    allowedRoles: ['psicologo_orientador'],
    anyOf: ['COUNSELING_VIEW', 'COUNSELING_CREATE', 'REFERRAL_CREATE', 'REFERRAL_EDIT'],
  },
  {
    path: 'soporte-tecnico/panel',
    to: '/soporte-tecnico/panel',
    label: 'Panel soporte',
    component: SoporteTecnicoPage,
    allowedRoles: ['soporte_tecnico_escolar'],
    anyOf: ['SUPPORT_VIEW_TICKETS', 'SUPPORT_CREATE_TICKET', 'SUPPORT_RESOLVE_TICKET', 'SUPPORT_RESET_PASSWORD'],
  },
  {
    path: 'bibliotecario-digital/panel',
    to: '/bibliotecario-digital/panel',
    label: 'Panel biblioteca',
    component: BibliotecarioDigitalPage,
    allowedRoles: ['bibliotecario_digital'],
    anyOf: ['LIBRARY_VIEW', 'LIBRARY_CREATE', 'LIBRARY_MANAGE_LOANS'],
  },
  {
    path: 'coordinador-academico/panel',
    to: '/coordinador-academico/panel',
    label: 'Panel academico',
    component: CoordinadorAcademicoPage,
    allowedRoles: ['coordinador_academico'],
    anyOf: ['PLANNING_VIEW', 'PLANNING_APPROVE'],
  },
  {
    path: 'apoderado/panel',
    to: '/apoderado/panel',
    label: 'Mi panel',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/mis-pupilos',
    to: '/apoderado/mis-pupilos',
    label: 'Mis pupilos',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/notas',
    to: '/apoderado/notas',
    label: 'Notas',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/asistencia',
    to: '/apoderado/asistencia',
    label: 'Asistencia',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/justificativos',
    to: '/apoderado/justificativos',
    label: 'Justificativos',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/firmas-pendientes',
    to: '/apoderado/firmas-pendientes',
    label: 'Firmas pendientes',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/perfil',
    to: '/apoderado/perfil',
    label: 'Mi perfil',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/calendario',
    to: '/apoderado/calendario',
    label: 'Calendario',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/comunicados',
    to: '/apoderado/comunicados',
    label: 'Comunicados',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/mensajes',
    to: '/apoderado/mensajes',
    label: 'Mensajes',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/mis-certificados',
    to: '/apoderado/mis-certificados',
    label: 'Mis certificados',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/admision-matricula',
    to: '/apoderado/admision-matricula',
    label: 'Admision y matricula',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/estado-cuenta',
    to: '/apoderado/estado-cuenta',
    label: 'Estado de cuenta',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'apoderado/mis-pagos',
    to: '/apoderado/mis-pagos',
    label: 'Mis pagos',
    component: ApoderadoPage,
    allowedRoles: ['apoderado'],
    anyOf: ['PORTAL_APODERADO'],
  },
  {
    path: 'planes',
    to: '/planes',
    label: 'Planes',
    component: PricingPage,
    anyOf: ['FINANCE_MANAGE_PAYMENTS', 'SYSTEM_ADMIN'],
  },
  {
    path: 'pagos/historial',
    to: '/pagos/historial',
    label: 'Historial de pagos',
    component: PaymentHistoryPage,
    anyOf: ['FINANCE_MANAGE_PAYMENTS', 'SYSTEM_ADMIN'],
  },
  {
    path: 'pagos/transferencias',
    to: '/pagos/transferencias',
    label: 'Transferencias',
    component: TransferNoticesPage,
    anyOf: ['FINANCE_MANAGE_PAYMENTS', 'SYSTEM_ADMIN'],
  },
];
