# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id_comunicado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('comunicado', '📋 Comunicado General'), ('evento', '📅 Evento'), ('citacion', '👥 Citación de Apoderados'), ('noticia', '📰 Noticia'), ('urgente', '🚨 Urgente')], default='comunicado', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('destinatario', models.CharField(choices=[('todos', 'Todos (Profesores, Estudiantes y Apoderados)'), ('profesores', 'Solo Profesores'), ('estudiantes', 'Solo Estudiantes'), ('apoderados', 'Solo Apoderados'), ('curso_especifico', 'Curso Específico')], default='todos', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto (PDF, imágenes, documentos)', null=True, upload_to='comunicados/%Y/%m/')),
                ('fecha_evento', models.DateTimeField(blank=True, help_text='Para eventos o citaciones', null=True)),
                ('lugar_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('requiere_confirmacion', models.BooleanField(default=False, help_text='¿Requiere confirmación de lectura?')),
                ('es_prioritario', models.BooleanField(default=False)),
                ('es_destacado', models.BooleanField(default=False, help_text='Aparece en banner principal')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='institucion.colegio')),
                ('cursos_destinatarios', models.ManyToManyField(blank=True, related_name='comunicados_recibidos', to='cursos.curso')),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'db_table': 'comunicado',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionLectura',
            fields=[
                ('id_confirmacion', models.AutoField(primary_key=True, serialize=False)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False, help_text='Para citaciones que requieren confirmación')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='comunicados.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_leidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmación de Lectura',
                'verbose_name_plural': 'Confirmaciones de Lectura',
                'db_table': 'confirmacion_lectura',
                'ordering': ['-fecha_lectura'],
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
