# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio_rbd', models.CharField(db_index=True, max_length=10, unique=True)),
                ('auditar_academico', models.BooleanField(default=True, help_text='Auditar notas, evaluaciones')),
                ('auditar_asistencia', models.BooleanField(default=True, help_text='Auditar asistencia')),
                ('auditar_comunicacion', models.BooleanField(default=True, help_text='Auditar comunicados, mensajes')),
                ('auditar_estudiantes', models.BooleanField(default=True, help_text='Auditar cambios en estudiantes')),
                ('auditar_usuarios', models.BooleanField(default=True, help_text='Auditar usuarios y roles')),
                ('auditar_seguridad', models.BooleanField(default=True, help_text='Auditar login, permisos')),
                ('dias_retencion', models.IntegerField(default=1825, help_text='Días de retención (5 años por defecto)')),
                ('auditar_visualizaciones', models.BooleanField(default=False, help_text='Auditar visualizaciones')),
                ('capturar_ip', models.BooleanField(default=True)),
                ('capturar_user_agent', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Auditoría',
                'verbose_name_plural': 'Configuraciones de Auditoría',
                'db_table': 'auditoria_configuracion',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_rut', models.CharField(blank=True, max_length=12, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_rol', models.CharField(blank=True, max_length=50, null=True)),
                ('colegio_rbd', models.CharField(db_index=True, max_length=10)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Modificar'), ('DELETE', 'Eliminar'), ('VIEW', 'Visualizar'), ('EXPORT', 'Exportar'), ('RESTORE', 'Restaurar')], db_index=True, max_length=10)),
                ('categoria', models.CharField(choices=[('academico', 'Académico'), ('asistencia', 'Asistencia'), ('comunicacion', 'Comunicación'), ('estudiantes', 'Estudiantes'), ('usuarios', 'Usuarios'), ('seguridad', 'Seguridad'), ('sistema', 'Sistema')], db_index=True, default='sistema', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tabla_afectada', models.CharField(db_index=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('valor_previo', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('campos_modificados', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítico')], db_index=True, default='info', max_length=10)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Eventos de Auditoría',
                'db_table': 'auditoria_evento',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['colegio_rbd', '-fecha_hora'], name='auditoria_e_colegio_fc6b10_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='auditoria_e_usuario_46b7e7_idx'), models.Index(fields=['tabla_afectada', '-fecha_hora'], name='auditoria_e_tabla_a_5804ae_idx'), models.Index(fields=['accion', 'categoria', '-fecha_hora'], name='auditoria_e_accion_e705e9_idx'), models.Index(fields=['nivel', '-fecha_hora'], name='auditoria_e_nivel_4798f3_idx')],
            },
        ),
    ]
