# Generated by Django 5.2.9 on 2026-01-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='aplica_matricula',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beca',
            name='aplica_mensualidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beca',
            name='aplica_otros_aranceles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beca',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EN_REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('VIGENTE', 'Vigente'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20),
        ),
    ]
