# Generated by Django 5.2.9 on 2026-01-27 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_claseestudiante'),
        ('institucion', '0003_cicloacademico'),
        ('matriculas', '0002_beca_aplica_matricula_beca_aplica_mensualidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-ciclo_academico__fecha_inicio', '-fecha_matricula'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.RemoveIndex(
            model_name='matricula',
            name='matricula_estudia_1fa61a_idx',
        ),
        migrations.RemoveIndex(
            model_name='matricula',
            name='matricula_estado_f4ebe0_idx',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='anio_escolar',
        ),
        migrations.AddField(
            model_name='matricula',
            name='ciclo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='institucion.cicloacademico'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estudiante', 'ciclo_academico'], name='matricula_estudia_312557_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estado', 'ciclo_academico'], name='matricula_estado_5a07c7_idx'),
        ),
    ]
