# Generated by Django 5.2.9 on 2026-01-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tardanza'), ('J', 'Justificada')], max_length=2)),
                ('tipo_asistencia', models.CharField(default='Presencial', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleInformeAcademico',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('nota_final', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nota_parcial_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nota_parcial_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nota_parcial_3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('clases_asistidas', models.IntegerField(default=0)),
                ('total_clases', models.IntegerField(default=0)),
                ('porcentaje_asistencia_asignatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario_profesor', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Informe Académico',
                'verbose_name_plural': 'Detalles de Informes Académicos',
                'db_table': 'detalle_informe_academico',
                'ordering': ['asignatura__nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tareas/entregas/%Y/%m/')),
                ('comentario_estudiante', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('revisada', 'Revisada'), ('tarde', 'Entrega Tardía')], default='entregada', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entrega de Tarea',
                'verbose_name_plural': 'Entregas de Tareas',
                'db_table': 'entrega_tarea',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_evaluacion', models.DateField()),
                ('ponderacion', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje de peso en el promedio (0-100%)', max_digits=5)),
                ('periodo', models.CharField(blank=True, choices=[('semestre1', 'Primer Semestre'), ('semestre2', 'Segundo Semestre'), ('trimestre1', 'Primer Trimestre'), ('trimestre2', 'Segundo Trimestre'), ('trimestre3', 'Tercer Trimestre'), ('bimestre1', 'Primer Bimestre'), ('bimestre2', 'Segundo Bimestre'), ('bimestre3', 'Tercer Bimestre'), ('bimestre4', 'Cuarto Bimestre')], max_length=20, null=True)),
                ('tipo_evaluacion', models.CharField(choices=[('formativa', 'Formativa'), ('sumativa', 'Sumativa'), ('diagnostica', 'Diagnóstica'), ('acumulativa', 'Acumulativa')], default='sumativa', max_length=20)),
                ('es_recuperacion', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluacion',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='InformeAcademico',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('semestre1', 'Primer Semestre'), ('semestre2', 'Segundo Semestre'), ('trimestre1', 'Primer Trimestre'), ('trimestre2', 'Segundo Trimestre'), ('trimestre3', 'Tercer Trimestre'), ('anual', 'Informe Anual')], max_length=20)),
                ('anio_escolar', models.IntegerField()),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('porcentaje_asistencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ranking_curso', models.IntegerField(blank=True, null=True)),
                ('total_estudiantes_curso', models.IntegerField(blank=True, null=True)),
                ('comentario_general', models.TextField(blank=True, null=True)),
                ('comentario_profesor_jefe', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informe Académico',
                'verbose_name_plural': 'Informes Académicos',
                'db_table': 'informe_academico',
                'ordering': ['-anio_escolar', '-periodo'],
            },
        ),
        migrations.CreateModel(
            name='MaterialClase',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='materiales/%Y/%m/')),
                ('tipo_archivo', models.CharField(choices=[('documento', 'Documento'), ('presentacion', 'Presentación'), ('video', 'Video'), ('audio', 'Audio'), ('imagen', 'Imagen'), ('otro', 'Otro')], default='documento', max_length=20)),
                ('es_publico', models.BooleanField(default=True, help_text='Si es público, los estudiantes pueden verlo')),
                ('tamanio_bytes', models.BigIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material de Clase',
                'verbose_name_plural': 'Materiales de Clase',
                'db_table': 'material_clase',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id_planificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('objetivo_general', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('anio_escolar', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planificación',
                'verbose_name_plural': 'Planificaciones',
                'db_table': 'planificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionActividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Actividad de Planificación',
                'verbose_name_plural': 'Actividades de Planificación',
                'db_table': 'planificacion_actividad',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionEvaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Evaluación de Planificación',
                'verbose_name_plural': 'Evaluaciones de Planificación',
                'db_table': 'planificacion_evaluacion',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionObjetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Objetivo de Planificación',
                'verbose_name_plural': 'Objetivos de Planificación',
                'db_table': 'planificacion_objetivo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionRecurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Recurso de Planificación',
                'verbose_name_plural': 'Recursos de Planificación',
                'db_table': 'planificacion_recurso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('instrucciones', models.TextField()),
                ('archivo_instrucciones', models.FileField(blank=True, null=True, upload_to='tareas/instrucciones/%Y/%m/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('es_publica', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
