# Generated by Django 6.0.1 on 2026-04-24 16:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_registroclase_firmaregistroclase'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institucion', '0009_solicitudreunion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadResoluble',
            fields=[
                ('id_actividad_resoluble', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('modalidad', models.CharField(choices=[('PDF', 'PDF'), ('ONLINE', 'Online'), ('MIXTA', 'Mixta')], default='PDF', max_length=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actividades/pdf/%Y/%m/')),
                ('requiere_aprobacion_docente', models.BooleanField(default=True)),
                ('auto_correccion_activa', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_resolubles', to='institucion.colegio')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Actividad Resoluble',
                'verbose_name_plural': 'Actividades Resolubles',
                'db_table': 'actividad_resoluble',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='IntentoResoluble',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('AUTOCORREGIDO', 'Autocorregido'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=30)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nota_sugerida', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('retroalimentacion', models.TextField(blank=True, default='')),
                ('requiere_revision_docente', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actividad_resoluble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='academico.actividadresoluble')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_resolubles_aprobados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_resolubles', to=settings.AUTH_USER_MODEL)),
                ('resultado_publicado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_intento_resoluble', to='academico.calificacion')),
            ],
            options={
                'verbose_name': 'Intento Resoluble',
                'verbose_name_plural': 'Intentos Resolubles',
                'db_table': 'intento_resoluble',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('actividad_resoluble', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaResoluble',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('respuesta_corta', 'Respuesta corta'), ('abierta', 'Abierta')], default='opcion_multiple', max_length=20)),
                ('enunciado', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('respuesta_correcta_texto', models.TextField(blank=True, default='')),
                ('respuesta_correcta_normalizada', models.TextField(blank=True, default='')),
                ('requiere_revision_docente', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('actividad_resoluble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='academico.actividadresoluble')),
            ],
            options={
                'verbose_name': 'Pregunta Resoluble',
                'verbose_name_plural': 'Preguntas Resolubles',
                'db_table': 'pregunta_resoluble',
                'ordering': ['orden', 'id_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPreguntaResoluble',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=300)),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='academico.preguntaresoluble')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta Resoluble',
                'verbose_name_plural': 'Opciones de Preguntas Resolubles',
                'db_table': 'opcion_pregunta_resoluble',
                'ordering': ['orden', 'id_opcion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaResoluble',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, default='')),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='academico.intentoresoluble')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='academico.opcionpreguntaresoluble')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='academico.preguntaresoluble')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_resolubles_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta Resoluble',
                'verbose_name_plural': 'Respuestas Resolubles',
                'db_table': 'respuesta_resoluble',
                'ordering': ['pregunta__orden', 'id_respuesta'],
                'unique_together': {('intento', 'pregunta')},
            },
        ),
    ]
