# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='anuncios/')),
                ('anclado', models.BooleanField(default=False)),
                ('enviar_email', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_creados', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='cursos.clase')),
                ('leido_por', models.ManyToManyField(blank=True, related_name='anuncios_leidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'db_table': 'anuncio',
                'ordering': ['-anclado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='cursos.clase')),
                ('participante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_p1', to=settings.AUTH_USER_MODEL)),
                ('participante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_p2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'conversacion',
                'ordering': ['-ultima_actividad'],
                'unique_together': {('clase', 'participante1', 'participante2')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='mensajes/')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.conversacion')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensaje',
                'ordering': ['fecha_envio'],
                'indexes': [models.Index(fields=['conversacion', 'fecha_envio'], name='mensaje_convers_2b622c_idx'), models.Index(fields=['receptor', 'leido'], name='mensaje_recepto_827169_idx')],
            },
        ),
    ]
