# Generated by Django 5.2.9 on 2026-01-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('institucion', '0003_cicloacademico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilestudiante',
            name='curso_actual_id',
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='ciclo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_actuales', to='institucion.cicloacademico'),
        ),
    ]
