# Generated by Codex on 2026-02-28

from django.db import migrations, models
import django.db.models.deletion


CAPABILITY_CODES = [
    'SYSTEM_ADMIN', 'SYSTEM_CONFIGURE', 'SYSTEM_VIEW_AUDIT', 'SYSTEM_MANAGE_SUBSCRIPTIONS',
    'DASHBOARD_VIEW_SELF', 'DASHBOARD_VIEW_SCHOOL', 'DASHBOARD_VIEW_ANALYTICS',
    'STUDENT_VIEW', 'STUDENT_CREATE', 'STUDENT_EDIT', 'STUDENT_DELETE',
    'STUDENT_VIEW_ACADEMIC', 'STUDENT_VIEW_DISCIPLINE', 'STUDENT_VIEW_CONFIDENTIAL',
    'TEACHER_VIEW', 'TEACHER_CREATE', 'TEACHER_EDIT', 'TEACHER_DELETE',
    'TEACHER_ASSIGN_COURSE', 'TEACHER_VIEW_PERFORMANCE',
    'COURSE_VIEW', 'COURSE_CREATE', 'COURSE_EDIT', 'COURSE_DELETE',
    'COURSE_ASSIGN_TEACHER', 'COURSE_ASSIGN_STUDENT',
    'CLASS_VIEW', 'CLASS_CREATE', 'CLASS_EDIT', 'CLASS_DELETE',
    'CLASS_TAKE_ATTENDANCE', 'CLASS_VIEW_ATTENDANCE',
    'GRADE_VIEW', 'GRADE_CREATE', 'GRADE_EDIT', 'GRADE_DELETE',
    'GRADE_PUBLISH', 'GRADE_VIEW_ANALYTICS',
    'ENROLLMENT_VIEW', 'ENROLLMENT_CREATE', 'ENROLLMENT_EDIT', 'ENROLLMENT_DELETE',
    'ANNOUNCEMENT_VIEW', 'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_EDIT', 'ANNOUNCEMENT_DELETE',
    'ANNOUNCEMENT_PUBLISH',
    'REPORT_VIEW_BASIC', 'REPORT_VIEW_ACADEMIC', 'REPORT_VIEW_FINANCIAL', 'REPORT_EXPORT',
    'FINANCE_VIEW', 'FINANCE_CREATE', 'FINANCE_EDIT', 'FINANCE_DELETE',
    'FINANCE_MANAGE_PAYMENTS', 'FINANCE_VIEW_SUBSCRIPTIONS',
    'USER_VIEW', 'USER_CREATE', 'USER_EDIT', 'USER_DELETE', 'USER_ASSIGN_ROLE',
    'AUDIT_VIEW', 'AUDIT_EXPORT',
]

ROLE_CAPABILITY_MAP = {
    'admin_general': CAPABILITY_CODES,
    'admin': [cap for cap in CAPABILITY_CODES if cap != 'SYSTEM_ADMIN'],
    'admin_escolar': [
        'SYSTEM_CONFIGURE', 'DASHBOARD_VIEW_SCHOOL', 'DASHBOARD_VIEW_ANALYTICS',
        'STUDENT_VIEW', 'STUDENT_CREATE', 'STUDENT_EDIT',
        'TEACHER_VIEW', 'TEACHER_CREATE', 'TEACHER_EDIT',
        'COURSE_VIEW', 'COURSE_CREATE', 'COURSE_EDIT',
        'CLASS_VIEW', 'CLASS_CREATE', 'CLASS_EDIT', 'CLASS_TAKE_ATTENDANCE',
        'GRADE_VIEW', 'GRADE_CREATE', 'GRADE_EDIT', 'GRADE_PUBLISH',
        'ENROLLMENT_VIEW', 'ENROLLMENT_CREATE', 'ENROLLMENT_EDIT',
        'ANNOUNCEMENT_VIEW', 'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_EDIT', 'ANNOUNCEMENT_PUBLISH',
        'REPORT_VIEW_BASIC', 'REPORT_VIEW_ACADEMIC', 'REPORT_VIEW_FINANCIAL', 'REPORT_EXPORT',
        'FINANCE_VIEW', 'FINANCE_MANAGE_PAYMENTS',
        'USER_VIEW', 'USER_CREATE', 'USER_EDIT', 'USER_ASSIGN_ROLE',
        'AUDIT_VIEW',
    ],
    'profesor': [
        'DASHBOARD_VIEW_SELF',
        'STUDENT_VIEW', 'STUDENT_VIEW_ACADEMIC',
        'CLASS_VIEW', 'CLASS_TAKE_ATTENDANCE', 'CLASS_VIEW_ATTENDANCE',
        'GRADE_VIEW', 'GRADE_CREATE', 'GRADE_EDIT',
        'ANNOUNCEMENT_VIEW', 'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_EDIT',
        'REPORT_VIEW_BASIC',
    ],
    'estudiante': [
        'DASHBOARD_VIEW_SELF', 'CLASS_VIEW', 'CLASS_VIEW_ATTENDANCE', 'GRADE_VIEW', 'ANNOUNCEMENT_VIEW',
    ],
    'apoderado': [
        'DASHBOARD_VIEW_SELF',
        'STUDENT_VIEW', 'STUDENT_VIEW_ACADEMIC',
        'CLASS_VIEW_ATTENDANCE', 'GRADE_VIEW', 'ANNOUNCEMENT_VIEW', 'FINANCE_VIEW',
    ],
    'asesor_financiero': [
        'DASHBOARD_VIEW_SCHOOL',
        'FINANCE_VIEW', 'FINANCE_CREATE', 'FINANCE_EDIT', 'FINANCE_DELETE',
        'FINANCE_MANAGE_PAYMENTS', 'FINANCE_VIEW_SUBSCRIPTIONS',
        'REPORT_VIEW_FINANCIAL', 'REPORT_EXPORT',
        'ANNOUNCEMENT_VIEW',
    ],
    'psicologo': [
        'DASHBOARD_VIEW_SCHOOL',
        'STUDENT_VIEW', 'STUDENT_VIEW_ACADEMIC', 'STUDENT_VIEW_CONFIDENTIAL',
        'REPORT_VIEW_ACADEMIC',
    ],
    'coordinador': [
        'DASHBOARD_VIEW_SCHOOL',
        'STUDENT_VIEW', 'STUDENT_VIEW_ACADEMIC',
        'TEACHER_VIEW',
        'GRADE_VIEW', 'GRADE_VIEW_ANALYTICS',
        'REPORT_VIEW_ACADEMIC',
    ],
    'inspector': [
        'DASHBOARD_VIEW_SCHOOL',
        'STUDENT_VIEW', 'STUDENT_VIEW_DISCIPLINE',
        'CLASS_TAKE_ATTENDANCE', 'CLASS_VIEW_ATTENDANCE',
        'ANNOUNCEMENT_VIEW',
    ],
}


ROLE_ALIASES = {
    'admin general': 'admin_general',
    'administrador general': 'admin_general',
    'super admin': 'admin_general',
    'admin_general': 'admin_general',
    'admin escolar': 'admin_escolar',
    'administrador escolar': 'admin_escolar',
    'admin_escolar': 'admin_escolar',
    'administrador': 'admin',
    'admin': 'admin',
    'profesor': 'profesor',
    'docente': 'profesor',
    'estudiante': 'estudiante',
    'alumno': 'estudiante',
    'apoderado': 'apoderado',
    'asesor financiero': 'asesor_financiero',
    'asesor_financiero': 'asesor_financiero',
    'psicologo': 'psicologo',
    'coordinador': 'coordinador',
    'inspector': 'inspector',
}


def _normalize_role_name(nombre):
    raw = (nombre or '').strip().lower()
    raw = ' '.join(raw.split())
    return ROLE_ALIASES.get(raw, raw.replace(' ', '_'))


def seed_capabilities_and_assignments(apps, schema_editor):
    Capability = apps.get_model('accounts', 'Capability')
    Role = apps.get_model('accounts', 'Role')
    RoleCapability = apps.get_model('accounts', 'RoleCapability')

    capability_by_code = {}
    for code in CAPABILITY_CODES:
        capability, _ = Capability.objects.get_or_create(
            code=code,
            defaults={'description': code.replace('_', ' ').title()},
        )
        capability_by_code[code] = capability

    for role in Role.objects.all():
        normalized_role = _normalize_role_name(role.nombre)
        role_capabilities = ROLE_CAPABILITY_MAP.get(normalized_role, [])
        for capability_code in role_capabilities:
            capability = capability_by_code.get(capability_code)
            if capability is None:
                continue
            RoleCapability.objects.get_or_create(
                role=role,
                capability=capability,
                defaults={'is_granted': True},
            )


def rollback_seed(apps, schema_editor):
    RoleCapability = apps.get_model('accounts', 'RoleCapability')
    Capability = apps.get_model('accounts', 'Capability')

    RoleCapability.objects.all().delete()
    Capability.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_legacy_curso_actual_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'db_table': 'capability',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='accounts.capability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Capability por Rol',
                'verbose_name_plural': 'Capabilities por Rol',
                'db_table': 'role_capability',
                'unique_together': {('role', 'capability')},
            },
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['role', 'capability'], name='role_capabi_role_id_53e9db_idx'),
        ),
        migrations.RunPython(seed_capabilities_and_assignments, rollback_seed),
    ]
