# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_matricula', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valor_mensual', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('RETIRADA', 'Retirada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('anio_escolar', models.IntegerField(default=2025)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='institucion.colegio')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matricula',
                'ordering': ['-anio_escolar', '-fecha_matricula'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(default=1)),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.IntegerField(default=2025)),
                ('monto_original', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_descuento', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_final', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago_completo', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('PAGADA_PARCIAL', 'Pagada Parcialmente'), ('VENCIDA', 'Vencida'), ('CONDONADA', 'Condonada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cuota',
                'ordering': ['anio', 'mes', 'numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOCIOECONOMICA', 'Socioeconómica'), ('RENDIMIENTO', 'Rendimiento Académico'), ('DEPORTIVA', 'Deportiva'), ('ARTISTICA', 'Artística'), ('HERMANOS', 'Descuento por Hermanos'), ('OTRO', 'Otro')], max_length=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('motivo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('SUSPENDIDA', 'Suspendida'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='becas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
                'db_table': 'beca',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('WEBPAY', 'Webpay (Tarjeta)'), ('CHEQUE', 'Cheque'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTRO', 'Otro')], max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='matriculas.cuota')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(max_length=50, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('detalle', models.TextField()),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/%Y/%m/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_anuladas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='matriculas.pago')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'db_table': 'boleta',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.IntegerField(default=2025)),
                ('total_deuda', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('ENVIADO', 'Enviado'), ('PAGADO', 'Pagado')], default='GENERADO', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='estados_cuenta/%Y/%m/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuenta', to='institucion.colegio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuenta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
                'db_table': 'estado_cuenta',
                'ordering': ['-anio', '-mes'],
                'indexes': [models.Index(fields=['estudiante', 'anio', 'mes'], name='estado_cuen_estudia_c1d56f_idx'), models.Index(fields=['colegio', 'estado'], name='estado_cuen_colegio_7999d8_idx')],
                'unique_together': {('estudiante', 'mes', 'anio')},
            },
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estudiante', 'anio_escolar'], name='matricula_estudia_1fa61a_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estado', 'anio_escolar'], name='matricula_estado_f4ebe0_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['colegio', 'estado'], name='matricula_colegio_a37900_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['matricula', 'estado'], name='cuota_matricu_61d737_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='cuota_estado_f260d0_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['anio', 'mes'], name='cuota_anio_3051ff_idx'),
        ),
        migrations.AddIndex(
            model_name='beca',
            index=models.Index(fields=['estudiante', 'estado'], name='beca_estudia_5f2bac_idx'),
        ),
        migrations.AddIndex(
            model_name='beca',
            index=models.Index(fields=['estado', 'fecha_inicio', 'fecha_fin'], name='beca_estado_7dbc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cuota', 'estado'], name='pago_cuota_i_c82d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estudiante', '-fecha_pago'], name='pago_estudia_ab1058_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado', 'fecha_pago'], name='pago_estado_ed32ad_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['estudiante', '-fecha_emision'], name='boleta_estudia_c6bc52_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['numero_boleta'], name='boleta_numero__02786d_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['estado'], name='boleta_estado_da6b60_idx'),
        ),
    ]
