# Generated by Django 5.2.9 on 2026-05-27 20:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_fix_foreignkey_integrity'),
        ('institucion', '0010_colegio_slug_logo_color_primario'),
        ('matriculas', '0003_alter_matricula_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdmision',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('apellido_paterno_estudiante', models.CharField(max_length=100)),
                ('apellido_materno_estudiante', models.CharField(max_length=100)),
                ('rut_estudiante', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento_estudiante', models.DateField(blank=True, null=True)),
                ('genero_estudiante', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=20)),
                ('direccion_hogar', models.CharField(blank=True, default='', max_length=255)),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=50)),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('TUTOR_LEGAL', 'Tutor Legal'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('certificado_nacimiento', models.FileField(blank=True, null=True, upload_to='admisiones/certificados_nacimiento/%Y/%m/')),
                ('certificado_medico', models.FileField(blank=True, null=True, upload_to='admisiones/certificados_medicos/%Y/%m/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('DOCUMENTOS_RECHAZADOS', 'Documentos Rechazados'), ('EN_LISTA_ESPERA', 'En Lista de Espera'), ('ACEPTADA', 'Aceptada (Cupo Reservado)'), ('FIRMADA', 'Contrato Firmado / Matriculado'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por el Apoderado')], default='PENDIENTE', max_length=30)),
                ('posicion_lista_espera', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_admision_apoderado', to=settings.AUTH_USER_MODEL)),
                ('ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_admision_ciclo', to='institucion.cicloacademico')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_admision', to='institucion.colegio')),
                ('curso_postulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_admision_curso', to='cursos.curso')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_admision_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Admisión',
                'verbose_name_plural': 'Solicitudes de Admisión',
                'db_table': 'solicitud_admision',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ContratoServicioEducacional',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('valor_arancel_anual', models.DecimalField(decimal_places=0, default=Decimal('2500000'), max_digits=10)),
                ('valor_matricula', models.DecimalField(decimal_places=0, default=Decimal('150000'), max_digits=10)),
                ('numero_cuotas', models.IntegerField(default=10)),
                ('titulo_contrato', models.CharField(default='Contrato de Prestación de Servicios Educacionales', max_length=200)),
                ('cuerpo_contrato', models.TextField()),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('ip_firma', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_firma', models.TextField(blank=True, null=True)),
                ('rut_firmante', models.CharField(blank=True, max_length=20, null=True)),
                ('firma_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('firma_token', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_apoderado', to=settings.AUTH_USER_MODEL)),
                ('ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_ciclo', to='institucion.cicloacademico')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_admision', to='institucion.colegio')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='matriculas.solicitudadmision')),
            ],
            options={
                'verbose_name': 'Contrato de Servicio Educacional',
                'verbose_name_plural': 'Contratos de Servicio Educacional',
                'db_table': 'contrato_servicio_educacional',
            },
        ),
    ]
