# Generated by Django 5.2.9 on 2026-01-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('cursos', '0001_initial'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.clase'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleinformeacademico',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.asignatura'),
        ),
        migrations.AddField(
            model_name='detalleinformeacademico',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.clase'),
        ),
        migrations.AddField(
            model_name='detalleinformeacademico',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_informe_profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='cursos.clase'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='evaluacion_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones', to='academico.evaluacion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.evaluacion'),
        ),
        migrations.AddField(
            model_name='informeacademico',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_academicos', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='informeacademico',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_academicos', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='informeacademico',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_academicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informeacademico',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleinformeacademico',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='academico.informeacademico'),
        ),
        migrations.AddField(
            model_name='materialclase',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cursos.clase'),
        ),
        migrations.AddField(
            model_name='materialclase',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='materialclase',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='cursos.clase'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='planificacionactividad',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.planificacion'),
        ),
        migrations.AddField(
            model_name='planificacionevaluacion',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.planificacion'),
        ),
        migrations.AddField(
            model_name='planificacionobjetivo',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='academico.planificacion'),
        ),
        migrations.AddField(
            model_name='planificacionrecurso',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='academico.planificacion'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='cursos.clase'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academico.tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('clase', 'estudiante', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('evaluacion', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='informeacademico',
            unique_together={('estudiante', 'periodo', 'anio_escolar')},
        ),
        migrations.AlterUniqueTogether(
            name='entregatarea',
            unique_together={('tarea', 'estudiante')},
        ),
    ]
