# Generated by Django 5.2.9 on 2026-01-27 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('institucion', '0003_cicloacademico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='anio_escolar',
        ),
        migrations.AddField(
            model_name='planificacion',
            name='ciclo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='institucion.cicloacademico'),
        ),
    ]
