# Generated by Django 5.2.9 on 2026-03-01 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_remove_planificacion_anio_escolar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Coordinador que aprobó/rechazó la planificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='enviada_por',
            field=models.ForeignKey(blank=True, help_text='Profesor que envió la planificación para revisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='observaciones_coordinador',
            field=models.TextField(blank=True, default='', help_text='Observaciones del coordinador académico al revisar la planificación'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20, null=True),
        ),
    ]
