# Generated by Django 6.0.1 on 2026-03-16 02:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_planificacion_aprobado_por_planificacion_enviada_por_and_more'),
        ('cursos', '0004_fix_foreignkey_integrity'),
        ('institucion', '0005_cicloacademico_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClase',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('numero_clase', models.PositiveIntegerField(default=1)),
                ('contenido_tratado', models.TextField()),
                ('tarea_asignada', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('hash_contenido', models.CharField(blank=True, default='', max_length=64)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_clase', to='cursos.clase')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_clase', to='institucion.colegio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_clase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Clase',
                'verbose_name_plural': 'Registros de Clase',
                'db_table': 'registro_clase',
                'ordering': ['-fecha', '-numero_clase'],
                'unique_together': {('clase', 'fecha', 'numero_clase')},
            },
        ),
        migrations.CreateModel(
            name='FirmaRegistroClase',
            fields=[
                ('id_firma', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FIRMADO', 'Firmado'), ('RECTIFICADO', 'Rectificado')], default='PENDIENTE', max_length=20)),
                ('firma_hash', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp_servidor', models.DateTimeField(default=django.utils.timezone.now)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_registro_clase', to=settings.AUTH_USER_MODEL)),
                ('registro_clase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_docente', to='academico.registroclase')),
            ],
            options={
                'verbose_name': 'Firma de Registro de Clase',
                'verbose_name_plural': 'Firmas de Registro de Clase',
                'db_table': 'firma_registro_clase',
                'ordering': ['-timestamp_servidor'],
            },
        ),
    ]
