# Generated by Django 5.2.9 on 2026-01-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveleducativo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
