# Generated by Django 5.2.9 on 2026-01-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_cicloacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloacademico',
            name='periodos_config',
            field=models.JSONField(default=dict, help_text='\n        Configuración de períodos: {\n            "periodos": [\n                {"nombre": "Primer Semestre", "inicio": "2024-03-01", "fin": "2024-07-31"},\n                {"nombre": "Segundo Semestre", "inicio": "2024-08-01", "fin": "2024-12-20"}\n            ]\n        }\n        '),
        ),
    ]
