# Generated by Django 5.2.9 on 2026-02-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_cicloacademico_periodos_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloacademico',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del ciclo académico', null=True),
        ),
    ]
