# Generated by Django 6.0.1 on 2026-03-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0006_colegio_tipo_configuracion_academica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionacademica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
