# Generated by Django 6.0.1 on 2026-04-03 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0007_alter_configuracionacademica_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionacademica',
            name='nota_aprobacion',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Nota mínima de aprobación (ej: 4.0 estándar Chile, 3.5 en algunos decretos)', max_digits=3),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='nota_maxima',
            field=models.DecimalField(decimal_places=1, default=7.0, help_text='Nota máxima de la escala (ej: 7.0 para Chile)', max_digits=3),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='nota_minima',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Nota mínima de la escala (ej: 1.0 para Chile)', max_digits=3),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='redondeo_decimales',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cantidad de decimales a redondear en notas (1 = un decimal)'),
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('feriado', '📅 Feriado'), ('vacaciones', '🏖️ Vacaciones'), ('evaluacion', '📝 Evaluación Institucional'), ('reunion', '👥 Reunión'), ('actividad', '🎯 Actividad'), ('ceremonia', '🎓 Ceremonia'), ('administrativo', '📋 Administrativo'), ('otro', '📌 Otro')], default='otro', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Para eventos de más de un día', null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('visibilidad', models.CharField(choices=[('todos', 'Todos'), ('profesores', 'Solo Profesores'), ('estudiantes', 'Solo Estudiantes'), ('apoderados', 'Solo Apoderados'), ('administrativos', 'Solo Administrativos')], default='todos', max_length=20)),
                ('es_feriado_nacional', models.BooleanField(default=False, help_text='No hay clases')),
                ('color', models.CharField(default='#3B82F6', help_text='Color hex para el calendario', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ciclo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='institucion.cicloacademico')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='institucion.colegio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento del Calendario',
                'verbose_name_plural': 'Eventos del Calendario',
                'db_table': 'evento_calendario',
                'ordering': ['fecha_inicio', 'hora_inicio'],
                'indexes': [models.Index(fields=['colegio', 'fecha_inicio'], name='evento_cale_colegio_0399cc_idx'), models.Index(fields=['tipo', 'fecha_inicio'], name='evento_cale_tipo_b559b1_idx')],
            },
        ),
    ]
