# Generated by Django 6.0.1 on 2026-04-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_jefe_utp_role_and_chile_capabilities'),
        ('institucion', '0008_configuracionacademica_nota_aprobacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('conductual', 'Conductual'), ('orientacion', 'Orientación'), ('administrativa', 'Administrativa'), ('general', 'General')], default='general', max_length=20)),
                ('fecha_propuesta', models.DateField(blank=True, null=True)),
                ('hora_propuesta', models.TimeField(blank=True, null=True)),
                ('fecha_confirmada', models.DateField(blank=True, null=True)),
                ('hora_confirmada', models.TimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual (videollamada)'), ('telefonica', 'Telefónica')], default='presencial', max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('enlace_virtual', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmada', '✅ Confirmada'), ('reprogramada', '🔄 Reprogramada'), ('rechazada', '❌ Rechazada'), ('completada', '✔️ Completada'), ('cancelada', '🚫 Cancelada')], default='pendiente', max_length=20)),
                ('observaciones_apoderado', models.TextField(blank=True, null=True)),
                ('respuesta_profesor', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reunion', to='accounts.apoderado')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reunion', to='institucion.colegio')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_como_tema', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Reunión',
                'verbose_name_plural': 'Solicitudes de Reunión',
                'db_table': 'solicitud_reunion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['profesor', 'estado'], name='solicitud_r_profeso_28754b_idx'), models.Index(fields=['apoderado', 'estado'], name='solicitud_r_apodera_a15c87_idx')],
            },
        ),
    ]
