# Generated by Django 5.2.9 on 2026-01-15 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoComunicado',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='comunicados/adjuntos/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('tamanio_bytes', models.BigIntegerField(default=0)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_adicionales', to='comunicados.comunicado')),
            ],
            options={
                'verbose_name': 'Adjunto de Comunicado',
                'verbose_name_plural': 'Adjuntos de Comunicados',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaComunicado',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('total_destinatarios', models.PositiveIntegerField(default=0, help_text='Número total de usuarios a los que se envió', verbose_name='Total de Destinatarios')),
                ('total_leidos', models.PositiveIntegerField(default=0, help_text='Número de usuarios que leyeron el comunicado', verbose_name='Total Leídos')),
                ('porcentaje_lectura', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de Lectura')),
                ('total_confirmados', models.PositiveIntegerField(default=0, help_text='Número de usuarios que confirmaron asistencia', verbose_name='Total Confirmados')),
                ('porcentaje_confirmacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de Confirmación')),
                ('destinatarios_profesores', models.PositiveIntegerField(default=0)),
                ('leidos_profesores', models.PositiveIntegerField(default=0)),
                ('destinatarios_estudiantes', models.PositiveIntegerField(default=0)),
                ('leidos_estudiantes', models.PositiveIntegerField(default=0)),
                ('destinatarios_apoderados', models.PositiveIntegerField(default=0)),
                ('leidos_apoderados', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio_lectura_horas', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo promedio entre publicación y primera lectura', max_digits=6, verbose_name='Tiempo Promedio de Lectura (horas)')),
                ('fecha_calculo', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('comunicado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='comunicados.comunicado')),
            ],
            options={
                'verbose_name': 'Estadística de Comunicado',
                'verbose_name_plural': 'Estadísticas de Comunicados',
            },
        ),
        migrations.CreateModel(
            name='PlantillaComunicado',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la plantilla', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('categoria', models.CharField(choices=[('general', '📋 General'), ('eventos', '📅 Eventos'), ('citaciones', '👥 Citaciones'), ('informes', '📊 Informes'), ('recordatorios', '⏰ Recordatorios'), ('emergencias', '🚨 Emergencias')], default='general', max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve de cuándo usar esta plantilla', verbose_name='Descripción')),
                ('titulo_plantilla', models.CharField(help_text='Puede incluir variables: {{nombre}}, {{curso}}, {{fecha}}, etc.', max_length=200, verbose_name='Título')),
                ('contenido_plantilla', models.TextField(help_text='Usa variables entre llaves: {{variable}}. Disponibles: {{nombre_estudiante}}, {{curso}}, {{fecha}}, {{hora}}, {{lugar}}, {{nombre_apoderado}}, {{rut_estudiante}}, {{nombre_colegio}}', verbose_name='Contenido')),
                ('tipo_default', models.CharField(choices=[('comunicado', '📋 Comunicado General'), ('evento', '📅 Evento'), ('citacion', '👥 Citación de Apoderados'), ('noticia', '📰 Noticia'), ('urgente', '🚨 Urgente')], default='comunicado', max_length=20, verbose_name='Tipo por Defecto')),
                ('destinatario_default', models.CharField(choices=[('todos', 'Todos (Profesores, Estudiantes y Apoderados)'), ('profesores', 'Solo Profesores'), ('estudiantes', 'Solo Estudiantes'), ('apoderados', 'Solo Apoderados'), ('curso_especifico', 'Curso Específico')], default='todos', max_length=20, verbose_name='Destinatario por Defecto')),
                ('requiere_confirmacion_default', models.BooleanField(default=False, verbose_name='Requiere Confirmación por Defecto')),
                ('es_prioritario_default', models.BooleanField(default=False, verbose_name='Es Prioritario por Defecto')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('veces_usada', models.PositiveIntegerField(default=0, help_text='Contador automático de usos', verbose_name='Veces Usada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_comunicados', to='institucion.colegio')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Comunicado',
                'verbose_name_plural': 'Plantillas de Comunicados',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['colegio', 'activa'], name='comunicados_colegio_0c08d5_idx'), models.Index(fields=['categoria'], name='comunicados_categor_63b45d_idx')],
            },
        ),
    ]
