# Generated by Django 5.2.9 on 2026-01-29 22:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0003_alter_curso_unique_together_curso_ciclo_academico_and_more'),
        ('institucion', '0004_cicloacademico_periodos_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ejemplo: '2024-2025'", max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('ACTIVO', 'Activo'), ('EVALUACION', 'En Evaluación'), ('FINALIZADO', 'Finalizado'), ('CERRADO', 'Cerrado')], default='PLANIFICACION', max_length=20)),
                ('periodos_config', models.JSONField(default=dict, help_text='\n        Configuración de períodos: {\n            "periodos": [\n                {"nombre": "Primer Semestre", "inicio": "2024-03-01", "fin": "2024-07-31"},\n                {"nombre": "Segundo Semestre", "inicio": "2024-08-01", "fin": "2024-12-20"}\n            ]\n        }\n        ')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_academicos_mejorados', to='institucion.colegio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_mejorados_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_mejorados_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo Académico Mejorado',
                'verbose_name_plural': 'Ciclos Académicos Mejorados',
                'db_table': 'ciclo_academico_mejorado',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('ACTIVO', 'Activo'), ('EVALUACION', 'En Evaluación'), ('FINALIZADO', 'Finalizado'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('ACTIVO', 'Activo'), ('EVALUACION', 'En Evaluación'), ('FINALIZADO', 'Finalizado'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField(blank=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_realizados', to=settings.AUTH_USER_MODEL)),
                ('ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='core.cicloacademico')),
            ],
            options={
                'verbose_name': 'Cambio de Estado',
                'verbose_name_plural': 'Cambios de Estado',
                'db_table': 'cambio_estado_ciclo',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='EstadoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PREMATRICULA', 'Pre-matrícula'), ('MATRICULADO', 'Matriculado'), ('ACTIVO', 'Activo'), ('INACTIVO_TEMPORAL', 'Inactivo Temporal'), ('SUSPENDIDO', 'Suspendido'), ('RETIRADO', 'Retirado'), ('GRADUADO', 'Graduado'), ('CERRADO', 'Cerrado')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('es_activo', models.BooleanField(default=True, help_text='Si el estudiante puede acceder al sistema')),
                ('permite_cambios', models.BooleanField(default=True, help_text='Si se permiten modificaciones en este estado')),
                ('requiere_documentacion', models.BooleanField(default=False, help_text='Si requiere documentación especial')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('transiciones_posibles', models.ManyToManyField(blank=True, help_text='Estados a los que se puede transitar desde este', to='core.estadomatricula')),
            ],
            options={
                'verbose_name': 'Estado de Matrícula',
                'verbose_name_plural': 'Estados de Matrícula',
                'db_table': 'estado_matricula',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaMejorada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('valor_matricula', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('numero_matricula', models.CharField(help_text='Número único de matrícula', max_length=20, unique=True)),
                ('ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.cicloacademico')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_mejoradas', to='institucion.colegio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_creadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_mejoradas', to='cursos.curso')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='core.estadomatricula')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_mejoradas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula Mejorada',
                'verbose_name_plural': 'Matrículas Mejoradas',
                'db_table': 'matricula_mejorada',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CambioEstadoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField(blank=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_matricula', to=settings.AUTH_USER_MODEL)),
                ('estado_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_desde', to='core.estadomatricula')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_hacia', to='core.estadomatricula')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='core.matriculamejorada')),
            ],
            options={
                'verbose_name': 'Cambio de Estado de Matrícula',
                'verbose_name_plural': 'Cambios de Estado de Matrícula',
                'db_table': 'cambio_estado_matricula',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddConstraint(
            model_name='cicloacademico',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio__lt', models.F('fecha_fin'))), name='ciclo_mejorado_fechas_validas'),
        ),
        migrations.AlterUniqueTogether(
            name='cicloacademico',
            unique_together={('colegio', 'nombre')},
        ),
        migrations.AddConstraint(
            model_name='matriculamejorada',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio__lte', models.F('fecha_fin')), ('fecha_fin__isnull', True), _connector='OR'), name='matricula_fechas_validas'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculamejorada',
            unique_together={('estudiante', 'ciclo_academico')},
        ),
    ]
