# Generated by Django 5.2.9 on 2026-03-01 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cursos', '0004_fix_foreignkey_integrity'),
        ('institucion', '0005_cicloacademico_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionConvivencia',
            fields=[
                ('id_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'Negativa'), ('NEUTRA', 'Neutra')], max_length=10)),
                ('categoria', models.CharField(choices=[('COMPORTAMIENTO', 'Comportamiento'), ('PUNTUALIDAD', 'Puntualidad'), ('UNIFORME', 'Uniforme'), ('CONVIVENCIA', 'Convivencia'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField()),
                ('gravedad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Moderada'), (3, 'Grave')], default=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificado_apoderado', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anotación de Convivencia',
                'verbose_name_plural': 'Anotaciones de Convivencia',
                'db_table': 'anotacion_convivencia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DerivacionExterna',
            fields=[
                ('id_derivacion', models.AutoField(primary_key=True, serialize=False)),
                ('profesional_destino', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('fecha_derivacion', models.DateField()),
                ('fecha_retorno', models.DateField(blank=True, null=True)),
                ('informe_retorno', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Derivación Externa',
                'verbose_name_plural': 'Derivaciones Externas',
                'db_table': 'derivacion_externa',
                'ordering': ['-fecha_derivacion'],
            },
        ),
        migrations.CreateModel(
            name='EntrevistaOrientacion',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(choices=[('ACADEMICO', 'Académico'), ('SOCIOEMOCIONAL', 'Socioemocional'), ('CONDUCTUAL', 'Conductual'), ('FAMILIAR', 'Familiar'), ('DERIVACION', 'Derivación')], max_length=20)),
                ('observaciones', models.TextField(help_text='Notas confidenciales de la entrevista')),
                ('acuerdos', models.TextField(blank=True, default='')),
                ('recomendaciones_profesor', models.TextField(blank=True, default='', help_text='Recomendaciones visibles para el profesor jefe (no confidenciales)')),
                ('seguimiento_requerido', models.BooleanField(default=False)),
                ('fecha_siguiente_sesion', models.DateField(blank=True, null=True)),
                ('confidencial', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrevista de Orientación',
                'verbose_name_plural': 'Entrevistas de Orientación',
                'db_table': 'entrevista_orientacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='JustificativoInasistencia',
            fields=[
                ('id_justificativo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ausencia', models.DateField()),
                ('fecha_fin_ausencia', models.DateField(blank=True, help_text='Dejar vacío si la ausencia fue de un solo día', null=True)),
                ('motivo', models.TextField()),
                ('tipo', models.CharField(choices=[('MEDICO', 'Médico'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='justificativos/%Y/%m/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('observaciones_revision', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Justificativo de Inasistencia',
                'verbose_name_plural': 'Justificativos de Inasistencia',
                'db_table': 'justificativo_inasistencia',
                'ordering': ['-fecha_ausencia'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoRecurso',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Préstamo de Recurso',
                'verbose_name_plural': 'Préstamos de Recursos',
                'db_table': 'prestamo_recurso',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='RecursoDigital',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('LIBRO', 'Libro'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento'), ('ENLACE', 'Enlace'), ('SOFTWARE', 'Software')], default='DOCUMENTO', max_length=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos_digitales/%Y/%m/')),
                ('url_externa', models.URLField(blank=True, default='')),
                ('publicado', models.BooleanField(default=False)),
                ('descargas', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurso Digital',
                'verbose_name_plural': 'Recursos Digitales',
                'db_table': 'recurso_digital',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('ACCESO', 'Problemas de acceso'), ('PLATAFORMA', 'Error en plataforma'), ('CONTRASEÑA', 'Reset de contraseña'), ('OTRO', 'Otro')], default='OTRO', max_length=12)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=8)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROGRESO', 'En progreso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=12)),
                ('resolucion', models.TextField(blank=True, default='')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'db_table': 'ticket_soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='anotacionconvivencia',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_convivencia', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='anotacionconvivencia',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role__nombre': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_convivencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anotacionconvivencia',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anotaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derivacionexterna',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_externas', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='derivacionexterna',
            name='derivado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derivacionexterna',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role__nombre': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_externas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrevistaorientacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas_orientacion', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='entrevistaorientacion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role__nombre': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas_orientacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrevistaorientacion',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificativoinasistencia',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativos_inasistencia', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='justificativoinasistencia',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role__nombre': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='justificativos_inasistencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificativoinasistencia',
            name='presentado_por',
            field=models.ForeignKey(help_text='Apoderado o encargado que presenta el justificativo', on_delete=django.db.models.deletion.PROTECT, related_name='justificativos_presentados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificativoinasistencia',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamorecurso',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recursos', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='prestamorecurso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recursodigital',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_digitales', to='cursos.asignatura'),
        ),
        migrations.AddField(
            model_name='recursodigital',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_digitales', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='recursodigital',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_digitales', to='institucion.niveleducativo'),
        ),
        migrations.AddField(
            model_name='recursodigital',
            name='publicado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos_publicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamorecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='core.recursodigital'),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soporte', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='reportado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_reportados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='anotacionconvivencia',
            index=models.Index(fields=['estudiante', '-fecha'], name='anotacion_c_estudia_8dcfac_idx'),
        ),
        migrations.AddIndex(
            model_name='anotacionconvivencia',
            index=models.Index(fields=['colegio', '-fecha'], name='anotacion_c_colegio_2a92df_idx'),
        ),
        migrations.AddIndex(
            model_name='anotacionconvivencia',
            index=models.Index(fields=['tipo'], name='anotacion_c_tipo_ca5fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacionexterna',
            index=models.Index(fields=['estudiante', '-fecha_derivacion'], name='derivacion__estudia_2212b8_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacionexterna',
            index=models.Index(fields=['estado'], name='derivacion__estado_a8f279_idx'),
        ),
        migrations.AddIndex(
            model_name='entrevistaorientacion',
            index=models.Index(fields=['estudiante', '-fecha'], name='entrevista__estudia_7a7ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='entrevistaorientacion',
            index=models.Index(fields=['psicologo', '-fecha'], name='entrevista__psicolo_b7ae4b_idx'),
        ),
        migrations.AddIndex(
            model_name='justificativoinasistencia',
            index=models.Index(fields=['estudiante', '-fecha_ausencia'], name='justificati_estudia_dc1afa_idx'),
        ),
        migrations.AddIndex(
            model_name='justificativoinasistencia',
            index=models.Index(fields=['estado'], name='justificati_estado_c5c86a_idx'),
        ),
        migrations.AddIndex(
            model_name='recursodigital',
            index=models.Index(fields=['colegio', 'tipo'], name='recurso_dig_colegio_43602a_idx'),
        ),
        migrations.AddIndex(
            model_name='recursodigital',
            index=models.Index(fields=['publicado'], name='recurso_dig_publica_0adcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamorecurso',
            index=models.Index(fields=['usuario', 'estado'], name='prestamo_re_usuario_f96139_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamorecurso',
            index=models.Index(fields=['recurso', 'estado'], name='prestamo_re_recurso_42ce03_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsoporte',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='ticket_sopo_estado_1ad43a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsoporte',
            index=models.Index(fields=['prioridad'], name='ticket_sopo_priorid_3f552f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsoporte',
            index=models.Index(fields=['asignado_a', 'estado'], name='ticket_sopo_asignad_d494de_idx'),
        ),
    ]
