# Generated by Django 5.2.9 on 2026-03-01 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anotacionconvivencia_derivacionexterna_and_more'),
        ('institucion', '0005_cicloacademico_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='ciclo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='institucion.cicloacademico'),
        ),
        migrations.AlterField(
            model_name='matriculamejorada',
            name='ciclo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_mejoradas_ciclo', to='institucion.cicloacademico'),
        ),
        migrations.DeleteModel(
            name='CicloAcademico',
        ),
    ]
