# Generated by Django 5.2.9 on 2026-03-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cambioestado_ciclo_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursodigital',
            name='es_plan_lector',
            field=models.BooleanField(default=False, help_text='Indica si el recurso pertenece al Plan Lector obligatorio'),
        ),
        migrations.AlterField(
            model_name='recursodigital',
            name='tipo',
            field=models.CharField(choices=[('LIBRO', 'Libro'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento'), ('ENLACE', 'Enlace'), ('SOFTWARE', 'Software'), ('MATERIAL_CRA', 'Material CRA/Didáctico')], default='DOCUMENTO', max_length=12),
        ),
    ]
